services:
  - type: web
    name: trendy-bot
    runtime: python
    pythonVersion: 3.10.12
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python fairy_beauty_bot.py"

